import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    // position: 'absolute',
    // width: '100%',
    // height: '100%',
    // flex: 1,
    flexDirection: 'column',
    backgroundColor: 'black',
  },
  preview: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  controls: {
    flex: 1,
    height: '100%',
    // height: 200,
    width: '100%',
    // maxWidth: 300,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  controlsTop: {
    // flex: 0,
    // height: '100%',
    // height: 200,
    width: '100%',
    // maxWidth: 300,
    // flexDirection: 'column',
    // justifyContent: 'space-between',
  },
  flashmode: {
    // position: 'absolute',
    // top: 0,
    // right: 0,
    // backgroundColor: '#fff',
  },
  controlsBottom: {
    flex: 0,
    // height: '100%',
    // height: 200,
    width: '90%',
    maxWidth: 300,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  controlBtn: {
    flex: 0,
    backgroundColor: '#fff',
    borderRadius: 50,
    padding: 15,
    // paddingHorizontal: 20,
    // alignSelf: 'center',
    // margin: 20,
  },
  pending: {
    flex: 1,
    backgroundColor: 'lightgreen',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
